name: Backend CI

on:
  push:
   paths:
    - 'email-writer-sb/**'
  pull_request:
   paths:
    - 'email-writer-sb/**' 

jobs:
    build:
        runs-on: ubuntu-latest

        env:
          GEMINI_URL: ${{ secrets.GEMINI_URL }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

        steps: 
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4   
          with:
            java-version: '21'
            distribution: 'temurin'
        
        - name: Build backend
          working-directory: email-writer-sb
          run: mvn clean package